---
- name: update SSL cert
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: update the cert
      include_role:
        name: issue_cert 
      vars:
        dns_name: "ansible.demoredhat.com"
