---
- name: Update SSL cert
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Update the cert
      ansible.builtin.include_role:
        name: issue_cert
      vars:
        issue_cert_dns_name: "ansible.demoredhat.com"
